### ISSUE TITLE
Jul 21 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#18]
# Security Reference Data Project Meeting
## Date
Jul 21 2020 - 11am EST / 4pm BST

## Untracked attendees
- Ben Sandler / AQR
- Julia Belford / Crux
- Lodovico Gavotti / Refinitiv
- Sagar Bora / Nomura

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Walk through new Agenda and meeting minute format (5 min)
- [ ] [SEC Consultation](https://www.sec.gov/rules/proposed/2020/34-89290.pdf) about optionality to use different identifiers for SEC reporting (15 min)
- [ ] Discuss details of workflow to add/update mappings (30 min). It was suggested to take a crowdsourcing/ consensus ranking.
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision was made to present the Issuer and Security Mapping ID project to a wider group of FINOS bank members on **August 18th**

## Action Items
- [ ] @saileshpandey to add a slide with the suggested crowdsourcing/ consensus ranking approach to the mapping workflow
- [ ] @saileshpandey to develop a plan and high level timeline for the securities reference data project (review project plan at next meeting and publish it ahead of the August 18th presentation)

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
Hi

**Comment by toshaellison** [comment]
Present

**Comment by aitana16** [comment]
hi!

**Comment by rcr203** [comment]
Here

**Comment by tonimcderment** [comment]
Hi

**Comment by adam-cardarelli** [comment]
hi

**Comment by PB-Crux** [comment]
Hi
