### ISSUE TITLE
Jul 21 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#20]
# Currency Reference Data Meeting
## Date
Jul 21 2020 - 10am EST / 3pm BST

## Untracked attendees
- Sourabh Sharma
- Ben Sandler / AQR
- Martin Price / Nomura
- Laurence Usher

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Agree on the data structure that will be used, attributes that are going to be represented (currency codes, onshore, offshore,...) (15 mins)
- [ ] How to work with and expand raw data (15 mins)
- [ ] Review slides to share with other banks and get content page together (15 mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- Considerations to keep in mind for creating documents:
a. agree on the scope - The group today agreed that initial scope should be Currencies, Currency pair and select precious metals (Gold, Silver, Platinum, and Palladium). The group felt that Crypto currency can be phase II.
b. Design of the process of contributing to the open store - @vijayesh-chandel to present the model for CDM in the next bi-weekly. Group to use that as the basis for Currency.
c. How to resolve data dispute - When 2 or more members have different view on a specific currency record/attribute? The group agreed that this can done after we complete # b

## Action Items
- [ ] @aitana16 to find out details regarding how to procure storage, who pays for it, guidelines around maintaining a store etc. 
- [ ] @saileshpandey @vijayesh-chandel to have an offline discussion to create project plan 
- [ ] @saileshpandey to create raw data (remove Nomura specific details)

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
Hi

**Comment by aitana16** [comment]
hi!

**Comment by Vijayesh-Chandel** [comment]
Hi!

**Comment by TSanborn-ISDA** [comment]
Greetings!

**Comment by rsiddharthan** [comment]
Hi

**Comment by yjo10** [comment]
Hello!

**Comment by tcrich99** [comment]
Hi

**Comment by saileshpandey** [comment]
1. Offline discussion to create project plan (Sailesh / Vijay)
2. Aitana to find out details regarding how to procure a store, who pays for it, guidelines around maintaining a store etc.
3. Create raw data (Sailesh) - hide Nomura specific details 
4. Few conisderation for creating the documents -
    a. agree on the scope - The group today agreed that initial scope should be Currencies, Currency pair and Commodities (precious metal). The group felt that Crypto currency can be phase II.
    b. Design of the process of contributing to the open store - Vijay to present the model for CDM in the next bi-weekly. Group to use that as the basis for Currency.
    c. How to resolve data dispute - When 2 or more members have different view on a specific curreny record/attribute? The group agreed that this can done after we complete # b

**Comment by TSanborn-ISDA** [comment]
Thanks Sailesh ofr all of your work on this topic!

Regarding 4a, I don't remember the suggestion of including currency pairs.  This inclusion could significantly increase the scope. I would suggest currencies and selected precious metals (e.g. Gold, Silver, Platinum, and Pallidium).
