### ISSUE TITLE
Aug 4th 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#21]
# Security Reference Data Project Meeting
## Date
Aug 4th 2020 - 11am EST / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [ ] Review and approve [July 21st meeting minutes](https://github.com/finos/secref-data/issues/18) (5 mins)
- [x] Present the high level **Project Plan** (Sailesh) (15 mins)
- [ ] Present the additional slide on how the dispute will be resolved (Sailesh) (10 mins)
- [ ] Present on the commercial side of getting a cloud store (Aitana) (5 mins)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
Hi

**Comment by PB-Crux** [comment]
HI

**Comment by aitana16** [comment]
hi!

**Comment by saileshpandey** [comment]
Project Plan - The following phases were proposed:
1. Phase I - Building Prototype & Socializing the project idea.
        Duration: Mar '20 - Sep '20. 
        Major upcoming Milestone: Presentation to a wider group on 18th Aug

2. Phase II - solution design & creating detailed execution plan
        Duration: Oct '20 - Dec '20

3.  Phase III - Execution 
        Duration: Realistic estimates to be availale after he design phase is complete.
