### ISSUE TITLE
Aug 4th 2020 - CurRef Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#22]
# Currency Reference Data Meeting
## Date
Aug 4th 2020 - 10am EST / 3pm BST

## Untracked attendees
- Sourabh Sharma / Nomura
- Ben Sandler / AQR

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Approve [July 7th](https://github.com/finos/secref-data/issues/19) and [July 21st](https://github.com/finos/secref-data/issues/20) CurRef Meeting minutes
- [ ] Walk through of Alloy and the Alloy pilot working group. 
- [ ] On-going work to submit changes back to ISDA CDM. Sailesh created the [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data)
- [ ] AOB, Q&A & Adjourn (5mins)
  - Reset index → reset for the currencies 
  - Do we need a unique ID above and beyond an ISO code?
  - Who is going to use the data/model we are coming up with? 

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Vijay and Sailesh → offline discussion for a project plan; roadmap
- [ ] Action items for Aitana on procuring storage → [Outstanding ODP requirement](https://github.com/finos/open-developer-platform/issues/154) 
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data

**Comment by brooklynrob** [comment]
I'm here

**Comment by iansloyan** [comment]
here!

**Comment by Vijayesh-Chandel** [comment]
Hi!

**Comment by TSanborn-ISDA** [comment]
Howdy!

**Comment by rsiddharthan** [comment]
Hi

**Comment by TSanborn-ISDA** [comment]
Sailesh - thanks for preparing the sample data.  Here are a few suggestions and thoughts:
1) Type - what are the domain of values that we have in mind?  I see precious metals as one.  How about "currency" as another one?
2) Status - looks like you have a copy/paste error on the rows for Gold and Silver
3) Precision - is there a standard precision value for Gold and Silver?  They are blank in your sample.
4) Rounding - If the group seeks to align with the Common Domain Model, then we might consider using an existing enum called Rounding, which can be observed in Alloy.  There are 3 values:  Up, Down, Nearest.
5) What is the intended cardinality and definitions for Vendor Code Type  and Vendor Code Value?

Thanks!
Ted Sanborn 
ISDA

**Comment by mpricey** [comment]
Better late than never
