### ISSUE TITLE
Currency Reference Data: Roadmap

### ISSUE THREAD

**Issue by agitana** [finos/secref-data#29]

**Comment by aitana16** [comment]
# Currency Reference Data Workstream – Project Plan Proposal 

## Stage 1 - Planning
- Agree on concept with participants and define a currency object
- Collate use cases to identify participants who want to get involved e.g. reg reporting
- Feasibility analysis – to get a view of commitment needed from participants
- Finos Technologies/Open Data Store – requirements review
- Milestone – WG to agree on plan for initiative
- Timeline – Aug 2020 to end of September 2020 (4 sessions)

## Stage 2 – Design (Part 1: Model)
- Design of a standardised agnostic currency ref data model using example data sets, Alloy Studio
- Initial focus on currency and commodities to formulate design
- Milestone – to agree on the model and submit it for build
- Timeline – October 2020 to end of November 2020 (4 sessions)

## Stage 3 – Design (Part 2: Workflow)

- Design of workflow – conflict resolutions, updating of data, cloud connectivity etc
- Milestone – to agree on the workflow design and submit it for build
- Timeline – December 2020 to mid-February 2021 (4 sessions)

## Stage 4 - Build

- Build and Testing (bandwidth TBC by Sailesh)
- Milestone – to have a working data retrieval from the cloud
- Timeline – mid-February 2021 to end of April 2021 (4 sessions)

/cc @saileshpandey @VijayeshChandel

**Comment by apapaioannou92** [comment]
@aitana16 can you give me edit access for this issue please, in order for me to edit the project plan according to the cur ref data meeting we had earlier today? thank you

**Comment by aitana16** [comment]
hi @apapaioannou92 unfortunately as you don't have CLA coverage I cannot enable the permissions for you to edit an issue created by me. Can you post the updates via comments and I'll make sure to add them into the plan? Thanks

**Comment by apapaioannou92** [comment]
- Stage 2 – Design (Part 1: Model) - deadline extended from end of November 2020 to end of December 2020
-  Milestone – to agree on the model and submit it for build - to be renamed to "to agree on the model and sign off from the Cur Ref Data working group"
-  Add as 1st milestone in Stage 4 - Build of the Project plan: "Confirm the model with ISO before publishing it into PROD"

**Comment by apapaioannou92** [comment]
> hi @apapaioannou92 unfortunately as you don't have CLA coverage I cannot enable the permissions for you to edit an issue created by me. Can you post the updates via comments and I'll make sure to add them into the plan? Thanks

-  Stage 2 – Design (Part 1: Model) - deadline extended from end of November 2020 to end of December 2020
-  Milestone – to agree on the model and submit it for build - to be renamed to "to agree on the model and sign off from the Cur Ref Data working group"
-  Add as 1st milestone in Stage 4 - Build of the Project plan: "Confirm the model with ISO before publishing it into PROD"

**Comment by aitana16** [comment]
> > hi @apapaioannou92 unfortunately as you don't have CLA coverage I cannot enable the permissions for you to edit an issue created by me. Can you post the updates via comments and I'll make sure to add them into the plan? Thanks
> 
> * Stage 2 – Design (Part 1: Model) - deadline extended from end of November 2020 to end of December 2020
> * Milestone – to agree on the model and submit it for build - to be renamed to "to agree on the model and sign off from the Cur Ref Data working group"
> * Add as 1st milestone in Stage 4 - Build of the Project plan: "Confirm the model with ISO before publishing it into PROD"

Thanks @apapaioannou92  I've updated the roadmap accordingly.

**Comment by apapaioannou92** [comment]
> > > hi @apapaioannou92 unfortunately as you don't have CLA coverage I cannot enable the permissions for you to edit an issue created by me. Can you post the updates via comments and I'll make sure to add them into the plan? Thanks
> > 
> > 
> > 
> > * Stage 2 – Design (Part 1: Model) - deadline extended from end of November 2020 to end of December 2020
> > * Milestone – to agree on the model and submit it for build - to be renamed to "to agree on the model and sign off from the Cur Ref Data working group"
> > * Add as 1st milestone in Stage 4 - Build of the Project plan: "Confirm the model with ISO before publishing it into PROD"
> 
> Thanks @apapaioannou92 I've updated the roadmap accordingly.

thanks!

**Comment by agitana** [comment]
closing this issue as it has been transferred to the Currency Reference Data project repository https://github.com/finos/curref-data/issues/12
