### ISSUE TITLE
Expand project to "Reference Data" and include "Currency Reference Data" and "Commodity Reference Data" workstreams 

### ISSUE THREAD

**Issue by mindthegab** [finos/secref-data#31]
Per https://github.com/finos/finos-fo/issues/38: 

Dear Project maintainers, 

given the growing interest we're seeing in reference data we'd like to propose to  expand the [Security Reference Data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/656834673/Security+Reference+Data+WG) project name to “Reference Data” and formalize inclusion of the  following three workstreams: 
  1. The existing “Security Reference Data” work
  2. The recently launched “Currency Reference Data” effort
  3. The Commodities Reference Data work which recently happened as a pilot on the Alloy platform and could find a natural home under this project

We envision this as largely a formality, as the the three efforts can evolve largely in parallel and operate by consensus until any definition of formal governance needs to be adopted for specific workstreams at a later stage (with our [new project governance template](https://github.com/copiesofcopies/community/tree/master/governance/Software-Projects) being a great starting point
 
Would be great for current maintainers to chime in and if needed discuss this at upcoming project meetings. 

For a broader context see: _Originally posted by @mindthegab in https://github.com/finos/finos-fo/issues/38#issuecomment-678567436_

**Comment by toshaellison** [comment]
This was discussed this during today's project meeting (https://github.com/finos/secref-data/issues/28) and there was consensus that it makes sense to expand the project, rename it, and include the additional workstreams.

There was additional discussion on the name and the group agreed to reflect on this over the next two weeks and make a decision at the next meeting. Key discussion points included:
- Whether or not "Security" accurately reflected the inclusion of currencies and commodities and whether it might be too narrow
- That reference data may be too broad
- Some potential new names raised include
          - Financial asset reference data
          - Asset reference data
          - Master data management
          - Open master data
          - Open financial reference data

The project community should continue to add ideas to this issue ahead of making a decision at the next meeting.

**Comment by agitana** [comment]
Closing this issue for the time being. Currency Reference Data is now a top level FINOS project hosted at https://github.com/finos/curref-data / cc @maoo @TheJuanAndOnly99
