### ISSUE TITLE
Sep 22nd 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#35]
# Currency Reference Data Meeting
## Date
09 22 2020 - 10am EST / 3pm BST

## Untracked attendees
_None_

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [Sep 8th meeting minutes](https://github.com/finos/secref-data/issues/32) - _meeting minutes were approved_
- [x] Update on Cloud Storage solution
    - Proposal to consider Git Large File Store: https://git-lfs.github.com/ - _given the size of the files that need to be stored, it was decided to use git large file store_
- [x] Review progress on [Project Plan](https://github.com/finos/secref-data/issues/29)
    - A decision was made to reach out to the community by September 25th and to start Stage 2 (Design) by early October
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- Given the size of the files that need to be stored, it was decided to use git large file store
- A decision was made to reach out to the community by September 25th and to start Stage 2 (Design) by early October

## Action Items
- @aitana16 to send updated draft for community reach out to @saileshpandey and @VijayeshChandel
- @saileshpandey to reach out to the community by September 25th

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by TSanborn-ISDA** [comment]
Present

**Comment by saileshpandey** [comment]
Hi

**Comment by RichardWagener365** [comment]
Hi

**Comment by toshaellison** [comment]
Present

**Comment by iansloyan** [comment]
Anseo

**Comment by aitana16** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
Hello!
