### ISSUE TITLE
Oct 6th 2020 - Currency Reference Data Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#36]
# Currency Reference Data Meeting
## Date
Oct 6th 2020 - 10am EST / 3pm BST

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [September 22nd meeting minutes](https://github.com/finos/secref-data/issues/35) - _meeting minutes were approved_
- [ ] Start [Project Plan **Stage 2 – Design (Part 1: Model)**](https://github.com/finos/secref-data/issues/29): design & initial focus of a standardised agnostic currency ref data model using example data sets, Alloy Studio - _The group stressed the importance of ensuring that the model is generic and incorporating additional product types_
- [ ] Review ISO [Currency codes](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1670774789/Currency+-+Defining+standard+Object) and [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data?search_id=d023d8fd-0e97-4ed5-9555-d91bc09fd487). - _Discussion points:_
    - ISO on-shore vs off-shore codes
    - ISO Country code: clarify whether it refers to the issuer country, the country where it's legal tender or something else. It was suggested to use "issuing authority" in order to accommodate EU (i.e. so that that field is not blank); other participants suggested to remove the field altogether
    - suggestion to use the ISO alpha-numeric code, while acknowledging that there may be cases where both the numeric and the alpha numeric ISO codes would be needed
    - it was asked whether this data source will provide any of:
        - international mapping?
        - swift code?
        - cross reference of different coding standards?
    - how would issuing body field apply to cryptocurrencies where there's no issuing body? - _value would just be zero as it is in precious metals_
    - suggestion to include one of the[ ISDA non-ISO codes](https://www.fpml.org/coding-scheme/non-iso-currency-1-0.xml) in the sample set to help in the analysis
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Next steps: look at other examples, see how to present ISO vs nonISO code and more clarity on issuing country/ authority.

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by TSanborn-ISDA** [comment]
Good morning!

**Comment by ElaineFraser** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
Hello

**Comment by toshaellison** [comment]
Present

**Comment by aitana16** [comment]
hi!

**Comment by saileshpandey** [comment]
Hi

**Comment by apapaioannou92** [comment]
hi
