### ISSUE TITLE
Oct 20th 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#39]
# Currency Reference Data Meeting
## Date
Oct 20th 2020 - 10am EST / 3pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [Oct 6th meeting minutes](https://github.com/finos/secref-data/issues/36)
- [x] Start [Project Plan Stage 2 – Design (Part 1: Model)](https://github.com/finos/secref-data/issues/29): design & initial focus of a standardized agnostic currency ref data model using example data sets, Alloy Studio
- [x] Review ISO [Currency codes](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1670774789/Currency+-+Defining+standard+Object) and [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data). - _Discussion points:_
    - ISO on-shore vs off-shore codes - _It was agreed that the field Non ISO code will be included in order to overcome this issue._
    - ISO Country code - _It was agreed that the field is renamed to Issuing Authority in order to accommodate "EU"._
    - Suggestion to use the ISO alpha-numeric code, while acknowledging that there may be cases where both the numeric and the alpha numeric ISO codes would be needed _It was agreed that the ISO numeric code field will be used._
    - it was asked whether this data source will provide any of:
        - international mapping? _This will be covered by providing: a) ISO codes, b) non-ISO codes, c) numeric codes._
        - swift code? _Participants suggested that swift code could be included as well in the data source._
        - cross reference of different coding standards? _Participants suggested that we can include that information in a module (details on what would be the primary code (ISO code vs non-ISO code)). The idea of introducing the field "FINOS code" as the primary key was recommended. FINOS code would not have a meaning and it would resolve the arising issue of different currency ids. Participants supported that a primary key without a connotation would make more sense._
    - how would issuing body field apply to cryptocurrencies where there's no issuing body? - _Cryptos should have some other field to identify issuing authority, since they have null values for ISO code and Issuing Authority._
    - _Recommendation of including a field that can capture the different classes of non-ISO codes._
    - _Suggestion to include one of the ISDA non-ISO codes in the sample set to help in the analysis_
    - _There was discussion around the ways that minor units, pound, pins, indicator for crosses, deliverable currency could be reflected in the data source._
    -  Other examples, see how to present ISO vs non-ISO code and more clarity on issuing country/authority.
- Include non-ISO codes in the sample?
- Add a non-ISO code offshore (CNH example was discussed)
- Couple of other additional fields for consideration:
   - Currency symbols (i.e. $, £, are used for preparing statements or confirmations, so you can write whatever the counterparty is used to seeing, instead of using the full ISO code) 
   - Suggestion to use aliases or "display versions" for those codes, which is what's done in the ISDA CDM
   - this may be lower priority and harder to represent in some technologies, may lead to character issues
   - agreement to leave this as a "nice to have"
   - minor unicode (indicates the precision, useful for conversion that can affect the calculation precision). Minor units (i.e. pound-pence, dollar-cent,...) 
   - Revisit this feature at the next session
   - do we want a way to represent crosses (i.e. any currency pair)? if so, it would be useful to have some indication as to what will be the market convention for a certain cross. 
   - ranking from 1-n of all the currencies and then the higher one is the lead currency. Problem arises with crosses like AUD-USD, there'd be use cases where the AUD would be the lead currency and the cross would be quoted in a number smaller than 1
   - group agreed that this is important, it would be useful to have a dataset that worked all the time and was maintained. 
   - Revisit this feature at the next session 
   - deliverable vs non-deliverable currencies; would be relevant and helpful to have such an indicator. 
   - Revisit this feature at the next session
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [x] _It was agreed that the field non-ISO code will be included in order to overcome this issue._
- [x] _It was agreed that the field is renamed to Issuing Authority in order to accommodate "EU"._
- [x] _It was agreed that the ISO numeric code field will be used._
- [x] _The International mapping in the data source will be covered by providing: a) ISO codes, b) non ISO codes, c) numeric codes._
- [x] _The swift code will be included as well in the data source._
- [x] _The idea of introducing as the primary key, a field named "FINOS code", which would not have a connotation, was promoted._ 
- [x] _Cryptos should have some other field to identify the issuing authority._

## Action Items
- [ ] Sailesh to submit non-ISO codes.
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
Hi

**Comment by ElaineFraser** [comment]
hi

**Comment by aitana16** [comment]
hello!

**Comment by toshaellison** [comment]
Present

**Comment by TSanborn-ISDA** [comment]
hi

**Comment by apapaioannou92** [comment]
hi
