### ISSUE TITLE
Nov 24th 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#44]
# Security Reference Data Project Meeting
## Date
Nov 24th 2020 - 11am EST / 4pm BST

## Untracked attendees
- Lodovico Gavotti / Refinitiv 
- Pascal Lefrancois / Inovestor
- Rob Underwood / FINOS
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Introduce new joiners & volunteers
- [ ] Approve [Nov 10th](https://github.com/finos/secref-data/issues/42) meeting minutes
- [ ] Review submitted use cases [#33](https://github.com/finos/secref-data/issues/33) - (use cases around data ingestion from new providers and duplicates had been scheduled to be submitted by Oct 27th, 2020)
- [ ] Review workflow [#26](https://github.com/finos/secref-data/issues/26)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by toshaellison** [comment]
Present

**Comment by apapaioannou92** [comment]
present

**Comment by sbora-nom** [comment]
Present

**Comment by RichardWagener365** [comment]
Hi

**Comment by cr20ro20** [comment]
present (Craig Rowe)

**Comment by rcr203** [comment]
here

**Comment by aitana16** [comment]
hi!
