### ISSUE TITLE
Currency Reference Data - Sample data

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#48]
| **FINOS Id** | **ISO Code** | **Non ISO Code** | **Numeric Code** | **Description**         | **ISO Issuing Authority code** | **Type**       | **Deliverable?** | **Onshore Indicator** | **Status** | **Precision** | **Rounding Rule** | **Start date** | **End date** | **Vendor Code Type (Not in scope for phase I)** | **Vendor code value (Not in scope for phase I)** |
| ------------ | ------------ | ---------------- | ---------------- | ----------------------- | ------------------------------ | -------------- | ---------------- | --------------------- | ---------- | ------------- | ----------------- | -------------- | ------------ | ----------------------------------------------- | ------------------------------------------------ |
|  |
| AUDxx        | AUD          |                  |                  | AUSTRALIAN DOLLAR       | AU                             |                |                  | Yes                   | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| CADxx        | CAD          |                  |                  | CANADIAN DOLLAR         | CA                             |                |                  | Yes                   | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| CNYxx        | CNY          |                  |                  | YUAN (CHINESE) RENMINBI | CN                             |                |                  |                       | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| EURxx        | EUR          |                  |                  | EURO                    |                                |                |                  |                       | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| GBPxx        | GBP          |                  |                  | BRITISH POUND           | GB                             |                |                  |                       | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| HKDxx        | HKD          |                  |                  | HONG KONG DOLLAR        | HK                             |                |                  |                       | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| INRxx        | INR          |                  |                  | INDIAN RUPEE            | IN                             |                |                  |                       | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| JPYxx        | JPY          |                  |                  | JAPANESE YEN            | JP                             |                |                  |                       | Active     | 0             | Down              |                |              |                                                 |                                                  |
| SGDxx        | SGD          |                  |                  | SINGAPORE DOLLAR        | SG                             |                |                  |                       | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| USDxx        | USD          |                  |                  | UNITED STATES DOLLAR    | US                             |                |                  |                       | Active     | 2             | Rounded           |                |              |                                                 |                                                  |
| AGxxx        | XAG          |                  |                  | Silver                  |                                | Precious Metal |                  |                       | Active     |               |                   |                |              |                                                 |                                                  |
| AUxxx        | XAU          |                  |                  | Gold                    |                                | Precious Metal |                  |                       | Active     |               |                   |                |              |                                                 |                                                  |

**Comment by agitana** [comment]
closing this issue as it has been transferred to the Currency Reference Data project repository 
https://github.com/finos/curref-data/issues/14
