### ISSUE TITLE
Dec 8th 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#49]
# Security Reference Data Project Meeting

 ## Date
Dec 8th 2020 - 11am ET / 4pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [Nov 10th](https://github.com/finos/secref-data/issues/42) meeting minutes
- [x] Approve [Nov 24th](https://github.com/finos/secref-data/issues/44) meeting minutes
- [x] Review workflow and next steps
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [x] Sailesh to send out an email to the participants asking for their willingness to contribute to this project. Final decision should be made in 2 weeks time from now. 
- [ ] Decision 2
- [ ] ...

## Action Items
- [x] Sailesh to send out an email to the participants asking for their willingness to contribute to this project. Final decision should be made in 2 weeks time from now. 
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by aitana16** [comment]
hi

**Comment by brooklynrob** [comment]
I'm here.

**Comment by TLATER** [comment]
o/

**Comment by RichardWagener365** [comment]
hi

**Comment by toshaellison** [comment]
Present

**Comment by apapaioannou92** [comment]
hi

**Comment by apapaioannou92** [comment]
closed
