### ISSUE TITLE
Dec 15th 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#50]
# Currency Reference Data Meeting
 ## Date
Dec 15th 2020 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [Dec 1st](https://github.com/finos/secref-data/issues/45) meeting minutes _- meeting minutes were approved_
- [x] Continue Project Plan Stage 2 – Design (Part 1: Model):
     - [x] Milestone – to agree on the model and submit it for build -Pending
- [ ] Review [ISO Currency codes](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1670774789/Currency+-+Defining+standard+Object) and [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data). _- this will be discussed next week in our model walkthrough meeting_
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [x] Stage 2 – Design (Part 1: Model) - deadline extended from end of November 2020 to end of December 2020
- [x] Milestone – to agree on the model and submit it for build - to be renamed to "to agree on the model and sign off from the Cur Ref Data working group"
- [x] Add as 1st milestone in Stage 4 - Build of the Project plan: "Confirm the model with ISO before publishing it into PROD"
- [ ] One of the next steps should be to review the model in a detailed manner from the working group.
- [ ] Even though FINOS has not heard back from ISO, first discussions with them indicated that most likely there will not be any roadblocks for the build of the model. Thus, it is ok for us to move forward with the design and development of the model. Before submitting the model for build in Stage 4 however, we need to cross-check with ISO.

## Action Items
- [x] Alex to adjust the project plan so that it can reflect the following items:
     - [x] Stage 2 – Design (Part 1: Model) - deadline extended from end of November 2020 to end of December 2020
     - [x] Milestone – to agree on the model and submit it for build - to be renamed to "to agree on the model and sign off from the Cur Ref Data working group"
     - [x] Add as 1st milestone in Stage 4 - Build of the Project plan: "Confirm the model with ISO before publishing it into PROD"
- [x] Alex to send out email about having next meeting on 22-Dec-2020 at 10am EST / 3pm GMT or early Jan-2021.
- [ ] Vijay to help Ted with debugging the arising compilation errors

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by ElaineFraser** [comment]
hi

**Comment by toshaellison** [comment]
present

**Comment by aitana16** [comment]
here

**Comment by Vijayesh-Chandel** [comment]
present

**Comment by apapaioannou92** [comment]
hi
