### ISSUE TITLE
Dec 22nd 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/secref-data#51]
# Currency Reference Data Meeting
 ## Date
20201222 - 10am ET / 3pm GMT

## Untracked attendees
- Ben Sandler / AQR

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [Dec 15th meeting minutes](https://github.com/finos/secref-data/issues/50) - _meeting minutes were approved_
- [x] Model walkthrough
    - **"isDeliverable"**: 
        - concerns about this field being called "nonDeliverable". If the boolean was "false", having a double false (i.e. non + false) could be confusing
         - it was discussed whether commodities are deliverable: they can be both. Commodities are eligible for delivery but as part of the trade it can be agreed not to deliver it 
         - it was discussed whether cryptocurrencies are deliverable
         - proposal to make the "isDeliverable" field optional in general, but mandatory for currencies. (set up constraints in Studio)
    - **"status"**: proposal to rename to "scheduled to be active"; or "retired"
    - **"type"**: "IssuanceTypeEnumeration": _funds_ WIR franc (Switzerland), COU (Colombia), UF (Chile). Question was raised as to whether we need to include all of these ISO codes (seems like yes), and if so, we'd need to find a better name for this field
    - **"Issuing Authority" description**: group was encouraged to review and submit comments either in Studio or via GitHub
- [ ] Review [ISO Currency codes](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1670774789/Currency+-+Defining+standard+Object) and [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data)
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] FINOS to connect with Hyperledger on cryptocurrencies (deliverable vs. nondeliverable)
- [ ] Review the following proposals at the next meeting
    - "isDeliverable" proposal to make this field optional (except for currencies, where it should be made mandatory -- set up constraints in Studio)
    - **"status"** field: proposal to rename to "scheduled to be active"; or "retired"
    - **"type"**: "IssuanceTypeEnumeration": _funds_ WIR franc (Switzerland), COU (Colombia), UF (Chile). Question was raised as to whether we need to include all of these ISO codes (seems like yes), and if so, we'd need to find a better name for this field
 - [ ] **"Issuing Authority" description**: all participants encouraged to review and submit comments on the descriptions either in Studio or via GitHub
- [x] "finosID" values: @elainefraser agreed to change the finosId values in the sample data to random strings so that they illustrate the intended use of the attribute as a "surrogate" value, meaning that it is not derived from the values in the record.

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by ElaineFraser** [comment]
hi

**Comment by toshaellison** [comment]
present

**Comment by aitana16** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
Hello!

**Comment by ElaineFraser** [comment]
Sample data in Studio project has been updated to replace the finosID alphanumeric values with guids
