### ISSUE TITLE
Jan 26th 2021 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/secref-data#53]
# Currency Reference Data Meeting
 ## Date
20210126 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve [Jan 12th meeting minutes](https://github.com/finos/secref-data/issues/52)
- [x] Review [proposal to update README.md file](https://github.com/agitana/secref-data/blob/master/README.md#currency-reference-data) @agitana 
    - [x]  Discuss socialization strategy: FINOS All Community call, community@ mailing list, FINOS social media, FINOS newsletter
- [ ] Update on open attributes @Vijayesh-Chandel
- [ ] Overview of reference data architecture - to be confirmed by @saileshpandey
- [ ] FINOS All Community call on Jan 27th @ 10am ET/ 3pm GMT (see [call in details](https://calendar.google.com/calendar/u/0/r/week/2021/1/27?eid=NDBrY204dTYxMnZmcXM3N2dubXZqZHM4cTggZmlub3Mub3JnX2ZhYzhtbzFyZmM2ZWhzY2cwZDgwZmk4amlnQGc&ctz=America/New_York&sf=true)) @agitana 
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Sailesh will provide an update on the data architecture and discuss next steps at the Feb 9th meeting

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by TSanborn-ISDA** [comment]
Good day everyone!

**Comment by agitana** [comment]
hi!

**Comment by ElaineFraser** [comment]
hi

**Comment by saileshpandey** [comment]
Hi

**Comment by apapaioannou92** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
hello
