### ISSUE TITLE
17-Mar-21 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by saileshpandey** [finos/secref-data#62]
# Currency Reference Data Meeting
 ## Date
17-Mar-21 - 10:30am ET / 3:30pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve past meeting minutes
- [x] Project Management - Overview of the process for setting Agenda & recording Minutes going forward
- [x] Architecture - Review of the Architecture, feedback and improvements [10 mins]
- [ ] Discuss the need for NDA from vendors (if any) and member firms [10 mins]
- [x] Currency Master - Process for creating the data set [5 mins]
- [x] Review action Item/ Agenda for next meeting.

## Decisions Made
- [ ] Group agreed to spend the last few minutes of every call to review the action item for the next call and agree on the agenda
- [ ] Group reviewed the proposed architecture and following agreement on the Workflow design was made -
- Usecase 1 - Adding a new Non ISO currency - Questionaire to capture the relevance/validity of the new code being added. The workflow engine to kick off approval process before committing to the store.
- Usecase 2 - Adding a new ISO currency - Group agreed to use feed to add/update ISO currency records. For fields added/updated via the ISO feed, the engine should initiate a review only workflow by Currency Ref data members. For fields to be derived or entered manually approval workflow should be kicked off before committing changes to the store.
- Usecase 3 - Retiring an old/unused currency code - Engine should trigger approval workflow to address the use case for retiring unused currencies - setting the status to Inactive/appropriate value.
 

## Action Items
- [ ] Sailesh to add the feedback on the Workflow design to the architecture document.
- [ ] Link to the Currency Data Model - request an account on the FINOS Legend Studio hosted instance at finos.org/legend in order to access the model at https://legend.finos.org/studio/viewer/UAT-38
- [ ] Group to review the initial data set that was created by Elaine and Vijay. This will give us an insight in to how to design the Workflow engine including validations that might be needed. Subsequently the group should exapnd the dataset to cover more ISO and Non ISO currencies.
- [ ] Vijay will  present refactoring of the IsOffShore and IsDeliverable flags in the model. [The idea behind it is that all currencies are deliverable at least locally (e.g. CNH is delivered locally onshore, and not delivered off shore hence the offshore currency CNY instead] so really we just need a single attribute for this]

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by RichardWagener365** [comment]
Thanks

**Comment by agitana** [comment]
Please know that we have created a mailing list for this work stream `currency-ref-data@finos.org` . Email currency-ref-data+subscribe@finos.org if you'd like to join. Email help@finos.org if you run into any issues

**Comment by saileshpandey** [comment]
Hi

**Comment by apapaioannou92** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
Hi

**Comment by TLATER** [comment]
o/

**Comment by TSanborn-ISDA** [comment]
hi

**Comment by rsiddharthan** [comment]
hi

**Comment by agitana** [comment]
## Untracked attendees
- Ben Sandler / AQR
- Jourik de Lange / Smartsream
- Raymond Korir / Individual contributor
- Vijayesh Chandel / GS
