### ISSUE TITLE
MAR 30 2021 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by saileshpandey** [finos/secref-data#64]
# Currency Reference Data Meeting
 ## Date
20210330 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x]  Group to review the initial data set that was created by Elaine and Vijay. This will give us an insight in to how to design the Workflow engine including validations that might be needed. Subsequently the group should exapnd the dataset to cover more ISO and Non ISO currencies.
- [x]  Vijay will present refactoring of the IsOffShore and IsDeliverable flags in the model. [The idea behind it is that all currencies are deliverable at least locally (e.g. CNH is delivered locally onshore, and not delivered off shore hence the offshore currency CNY instead] so really we just need a single attribute for this]
- [ ] Discuss the need for NDA from vendors (if any) and member firms [10 mins]
- [ ] AOB 
- [x] Review action Item/ Agenda for next meeting.

## Decisions Made
- [x] Group discussed on how we could model minor currency. Suggestion was to use No Iso code and further use divisor to account for conversion to major currency denom
- [ ] Vijay explained the rationale behind modelling one field - IsOffshore instead of using both IsOffshore and IsDeliverable as all currencies are deliverable locally at least. Jourik raised some concerns with this approach.  The group agreed to discuss further and close this point in subsequent calls.
- [ ] agreement on spending some time on the next few calls to take the implementation approach forward. 
- [ ] Top agenda for next call would be - 1.  Talk about the need for NDA from member firms and vendors; 2. Create initial list for building the currency Master.

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by ElaineFraser** [comment]
hi

**Comment by rsiddharthan** [comment]
hi

**Comment by RichardWagener365** [comment]
hi

**Comment by agitana** [comment]
## Untracked attendees
- Alexander Papaioannou / Nomura
- Jourik de Lange / Smartstream
- Ian Sloyan / ISDA
- Vijayesh Chandel / GS
- Tosha Ellison / FINOS
