### ISSUE TITLE
Apr 13 2021 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by saileshpandey** [finos/secref-data#65]
# Currency Reference Data Meeting
 ## Date
2021-04-13 - 10am ET / 3pm GMT

## Untracked attendees
- Jourik Delange / Smartstream
- Nigel Cobb / Regnosys

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [March 30th meeting minutes](https://github.com/finos/secref-data/issues/64) - _meeting minutes were approved_
- [x] Discuss the need for NDA from vendors (if any) and member firms [10 mins]
- [ ] Create / Review initial list for building the currency Master. [10 mins]
- [ ] Review action Item/ Agenda for next meeting.
- [ ] AOB
 

## Decisions Made
- [ ] Tosha  clarified that FINOS lawyers have confirmed that CCLA is sufficient and no NDA would be required. She would reach out again to get an explicit confirmation about sharing of data as the CCLA is build around sharing of codes.
- [ ] Group agreed to review, in the next meeting,  the initial list of ISO currency that Sailesh will upload to the confluence page. Following that Group agreed to discuss the design approach and gradually build the implementation plan.
- [ ] Group agreed to focus on ISO currency for the initial build and push everything to subsequent phases- minor currency, Digital currency, Precious metals etc.
- [ ] Jourik suggested to reach out to ISo to get an agreement that Non ISO codes for  minor  & offshore currencies will be reserved.

## Action Items
- [ ] Sailesh to upload the ISO currency specific data to the confluence page - https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data 
- [ ]  Tosha to reach out  to FINOS legal team to get an explicit confirmation on feasibility of sharing data as opposed to sharing of code.

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by ElaineFraser** [comment]
hi

**Comment by saileshpandey** [comment]
Hi

**Comment by agitana** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
hi

**Comment by iansloyan** [comment]
hello

**Comment by Vijayesh-Chandel** [comment]
Hi All - Have updated the definition of isDeliverable field in the model as discussed in WG (pasting here too)

isDeliverable:
_Indicates if a currency is deliverable outside of the issuing authority's location.  False indicates that it is either not deliverable or deliverability is not applicable, for example with precious metals. True indicates that it is deliverable._
