### ISSUE TITLE
Nov 9th 2021 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/secref-data#77]
# Currency Reference Data Meeting
[Currency Reference data overview, roadmap and background](https://github.com/finos/secref-data#currency-reference-data)

## Date
20211109 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes - _approved_
- [x] CurRef Data repository walkthrough (Aitana Myohl)
- [x] Discuss the next step for data storage 
- [x] Focus on the basic use case of how to handle a change to an existing data set. (15 mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by ElaineFraser** [comment]
Regarding Yourik's comment last week about recent ISO changes, here is the ISO update notice:

The Bolívar Soberano (VES) is redenominated by removing six zeros from the denominations. A new
currency code VED/926 representing the new valuation (1,000,000 times old VES/928) is introduced on 1
October 2021 for any internal needs during the redenomination process, but is not replacing VES as the
official currency code. The Central Bank of Venezuela will not adopt the new codes in the local system,
VES/928 remains in use.
The actual currency code VES/928 remains the valid code after 1 October 2021 to use in any future
transactions to indicate the redenominated Bolívar Soberano.
Until further notice, VES/928 and VED/926 remain on "List one: Currency, fund and precious metal
codes".

It doesn't sound, from this description, like the new code would be actively used in a trading context.

**Comment by ElaineFraser** [comment]
hi

**Comment by saileshpandey** [comment]
Hi

**Comment by Jourik-de-Lange** [comment]
Hi All, im attending today

**Comment by saileshpandey** [comment]
1. New Currency - If the data set is incomplete? have we defined a mandatory set of fields for creation
2. New Currency - If the data set from two contributors don't match
3. How do we handle requests to add new currency not in the repository yet? - We should ask for prospectus and other relevant details. Question is we should have a general request template etc. But this use case will require deeper analysis to understand how we can handle it.
General thought - we should  do a pre check before add  / update of records. 
We should look at what we can automate and what we can absorb using a well defined process / guidelines

**Comment by agitana** [comment]
meeting minutes approved at the [January 18th Currency Reference Data meeting](https://github.com/finos/curref-data/issues/6)
