### ISSUE TITLE
Nov 23rd 2021 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/secref-data#78]
# Currency Reference Data Meeting
[Currency Reference data overview, roadmap and background](https://github.com/finos/secref-data#currency-reference-data)

## Date
20211123 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Data storage and changes to existing datasets (see https://github.com/finos/secref-data/issues/77#issuecomment-964262983) (Sailesh Pandey)
- [ ] Review of a proposal for automated checks on new/changed list entries (Elaine Fraser)
- [ ] Discuss what the ‘next category’ of list entries should be (Elaine Fraser)
- [ ] Cryptocurrencies (Elaine Fraser)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by ElaineFraser** [comment]
hi

**Comment by iansloyan** [comment]
I cannot get the Webex to work? am I alone in this?

**Comment by agitana** [comment]
hi @iansloyan we adjourned today's meeting early due to a lack of quorum and will regroup on December 7th

**Comment by iansloyan** [comment]
Ok – there was an error on webex I have never seen. Which might have caught others.

Error as follows:
“
Cisco WebEx had a problem processing your request. Contact support or your administrator and provide the following error tracking ID:
3CF2D3458A1F41B9AD487BAD1E9979DA_1637679814784.

”

**Comment by Julia-Ritter** [comment]
Julia /FINOS

**Comment by agitana** [comment]
> Ok – there was an error on webex I have never seen. Which might have caught others. Error as follows: “ Cisco WebEx had a problem processing your request. Contact support or your administrator and provide the following error tracking ID: 3CF2D3458A1F41B9AD487BAD1E9979DA_1637679814784. ” From: agitana ***@***.***> Sent: Tuesday 23 November 2021 15:16 To: finos/secref-data ***@***.***> Cc: Ian Sloyan ***@***.***>; Mention ***@***.***> Subject: Re: [finos/secref-data] Nov 23rd 2021 - Currency Ref Data Meeting Minutes (Issue #78) EXTERNAL EMAIL hi @iansloyan<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_iansloyan&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=n1VJAbqAEVWX_WUt4rRtwQ&m=HImTErQ_2ZOf5Vru-g2RoRiD6Mt7Gm3KOo8PIa-ghGg&s=q7dl4X06rpA1ec52nD4Bt_MY9uQZi4tkfkJrBELC5ts&e=> we adjourned today's meeting early due to a lack of quorum and will regroup on December 7th — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_finos_secref-2Ddata_issues_78-23issuecomment-2D976696309&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=n1VJAbqAEVWX_WUt4rRtwQ&m=HImTErQ_2ZOf5Vru-g2RoRiD6Mt7Gm3KOo8PIa-ghGg&s=cpfEGqDob0MKai5ig0qEk1l4dmW_5n1BCooXL--nQa8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOV6OGB5JLYOUIZWEF3H6NTUNOV35ANCNFSM5IRHT4VA&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=n1VJAbqAEVWX_WUt4rRtwQ&m=HImTErQ_2ZOf5Vru-g2RoRiD6Mt7Gm3KOo8PIa-ghGg&s=6WrLoZMGCf_6zGgmN92zLH-Zi23sv_cSo6fj6GpEij8&e=>. The information contained in either this email and, if applicable, the attachment, are confidential and are intended only for the recipient. The contents of either the email or the attachment may not be disclosed or used by anyone other than the addressee. If you are not the intended recipient(s), any use, disclosure, copying, or distribution is prohibited and may be unlawful. If you have received this communication in error, please notify us by e-mail at ***@***.******@***.***> then delete the e-mail and all attachments and any copies thereof.

thank you for flagging this @iansloyan, we'll look into it
